### PR TITLE
Header and Footer PR

### PR DESCRIPTION
**Pull request by J4VJ4R**
This is a pullrequest between header and footer

Please give me a review of my landing page [here](https://laslesvpn-test.herokuapp.com/),  thanks.

### CODE REVIEW

**Comment by Charliemur2-zz** [comment]
I am adding some pictures that show the original design over your page.
The scroll to top button is not on the footer.
Something looks diferent in the line spacing on footer's navigation links.
Captura de Pantalla 2021-03-18 a la(s) 9 56 57 a  m
Captura de Pantalla 2021-03-18 a la(s) 9 57 15 a  m
Captura de Pantalla 2021-03-18 a la(s) 10 03 10 a  m
Captura de Pantalla 2021-03-18 a la(s) 10 07 17 a  m
Captura de Pantalla 2021-03-18 a la(s) 10 08 30 a  m

**Comment by J4VJ4R** [comment]
Please give me a new review on PR and here a link to preview on heroku https://laslesvpn-test.herokuapp.com/

**Comment by CrispthoAlex** [comment]
The Sass structure is good.
Fix gap between buttons for Mobile and medium version.

You can merge!!!

**Comment by J4VJ4R** [comment]
After the reviewer, we fixed issues and then we confirmed pr

**Pull request merged**
